/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.suse.skleaner

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        assertNotNull("Hi", "app should have a greeting")
    }
}
